version: '3'
services:
  db-books-api:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: books-api